Isics\FlatPageBundle\Entity\FlatPage:
    properties:
        url:
            - NotBlank: ~
        title:
            - NotBlank: ~
        content:
            - NotBlank: ~
        templateName:
            - NotBlank: ~
        isPublished:
            - NotNull: ~
